In [19]:
import numpy as np
import pickle

In [103]:
class cryoEM:
    
    def __init__(self, file_dir):
        with open(file_dir, 'rb') as file:
            with np.load(file, allow_pickle = True) as data:
                self.samples = data["samples"]
                self.noiselevels = data["noiselevels"]
                self.shiftSD = data["shiftSD"]
                self.myImage = data["myImage"]

In [101]:
test = cryoEM(file_dir = "2dImages.npz")
print(test.samples)

[[[[ 4.03037430e+00  2.01518715e+00  6.71729050e-01]
   [ 9.96808514e-01  4.98404257e-01  1.66134752e-01]
   [-3.15454964e+00 -1.57727482e+00 -5.25758274e-01]
   ...
   [-6.14446760e-01 -3.07223380e-01 -1.02407793e-01]
   [ 8.40944503e-01  4.20472251e-01  1.40157417e-01]
   [-9.88214670e+00 -4.94107335e+00 -1.64702445e+00]]

  [[-1.07849914e+00 -5.39249571e-01 -1.79749857e-01]
   [-6.25284752e+00 -3.12642376e+00 -1.04214125e+00]
   [-4.71346330e-01 -2.35673165e-01 -7.85577217e-02]
   ...
   [-1.98349314e+00 -9.91746570e-01 -3.30582190e-01]
   [-3.42924775e+00 -1.71462388e+00 -5.71541292e-01]
   [-3.51971489e+00 -1.75985744e+00 -5.86619148e-01]]

  [[ 9.29062203e+00  4.64531102e+00  1.54843701e+00]
   [-1.93586843e+00 -9.67934213e-01 -3.22644738e-01]
   [ 8.51300058e+00  4.25650029e+00  1.41883343e+00]
   ...
   [ 5.18245797e-01  2.59122898e-01  8.63742994e-02]
   [ 3.68273463e+00  1.84136731e+00  6.13789104e-01]
   [ 5.29175083e+00  2.64587541e+00  8.81958471e-01]]

  ...

  [[-1.10228